resources:
  - name: repo_java_image
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-multiple-pipeline-config-files    # replace with your repository name
      branches:
        include: master
      files:
        include: ^java-image\/.+

  - name: repo_node_image
    type: GitRepo
    configuration:
      gitProvider: manishas_github   # replace with your integration
      path: manishas-jfrog/example-multiple-pipeline-config-files    # replace with your repository name
      branches:
        include: master
      files:
        include: ^node-image\/.+

  - name: bi_java
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: java_image
      buildNumber: 1

  - name: bi_node
    type: BuildInfo
    configuration:
      sourceArtifactory: demoArt
      buildName: node_image
      buildNumber: 1

pipelines:
  - name: pipeline_build_node_image
    steps:
      - name: docker_build_node
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: manishas.jfrog.io/docker-local/node_image
          dockerImageTag: ${run_number}
          inputResources:
            - name: repo_node_image
          integrations:
            - name: demoArt

      - name: docker_push_node
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build_node

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_node
          outputResources:
            - name: bi_node

  - name: pipeline_build_java_image
    steps:
      - name: docker_build_java
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: manishas.jfrog.io/docker-local/java_image
          dockerImageTag: ${run_number}
          inputResources:
            - name: repo_java_image
          integrations:
            - name: demoArt

      - name: docker_push_java
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: demoArt
          inputSteps:
            - name: docker_build_java

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push_java
          outputResources:
            - name: bi_java
